image: shadowrobot/build-tools:trusty-indigo
stages:
  - build

sr-build-tools-build:
  stage: build
  tags:
    - docker
  script:
    - export toolset_branch="master"
    - export server_type="gitlab_ci"
    - export used_modules="check_cache,code_coverage,software_tests,code_style_check,complete_deb_check"
    - export unit_tests_result_dir="unit_tests"
    - export coverage_tests_result_dir="code_coverage"
    - export lint_result_dir="lint_results"
    - export docker_image_name="shadowrobot/build-tools:trusty-indigo"
    - export remote_shell_script="https://raw.githubusercontent.com/T045T/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh"
    - curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash /dev/stdin "$toolset_branch" $server_type $used_modules $relative_job_path
  artifacts:
    paths:
      - unit_tests/
      - code_coverage/
      - lint_results/
