variables:
  CI_SCRIPTS_BRANCH: master
  DOCS_SOURCE: "ros_bt_py/doc/source"


.build_matrix:
  parallel:
    matrix:
      - ROS_DISTRO: noetic
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_ros

stages:
  - check
  - build
  - upload
  - deploy

include:
  - project: "continuous_integration/ci_scripts"
    ref: master
    file: "/gitlab-ci-yml/catkin_pipeline.yml"
  - project: "continuous_integration/ci_scripts"
    ref: master
    file: "/gitlab-ci-yml/doc_sphinx.yml"

clang-tidy-check:
  allow_failure: true
