variables:
  CI_SCRIPTS_BRANCH: master

catkin_pipelines:
  trigger:
    include:
      - project: 'continuous_integration/ci_scripts'
        ref: $CI_SCRIPTS_BRANCH
        file: '/gitlab-ci-yml/catkin_pipeline_v2.yml'
    strategy: depend
  parallel:
    matrix:
      - ROS_DISTRO: noetic
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_ros
