include:
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/include/catkin_build.yml'
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/include/catkin_check.yml'
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/include/catkin_upload.yml'
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/include/cpp_check.yml'

stages:
  - check
  - build
  - test
  - upload

before_script:
  - source /opt/ros/${ROS_DISTRIBUTION}/setup.bash

variables:
  # This is used to actually get the ci_scripts submodule
  GIT_STRATEGY: clone
  ROSDISTRO_INDEX_URL: http://ids-ubuntu-testing.fzi.de:8000/rosdistro/index-v4.yaml
  CI_SCRIPTS_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@ids-git.fzi.de/continuous_integration/ci_scripts

  ROS_DISTRIBUTION: kinetic # This will be overwritten once ROS is sourced

  CATKIN_ROOT: ${HOME}/catkin_workspace

  BUILD_INDIGO: "false"

.clang-tidy-check:
  tags:
    - docker
  stage: check
  script:
    - apt-get -y update
    - git clone ${CI_SCRIPTS_REPO} ${HOME}/ci_scripts
    - cp ${HOME}/ci_scripts/catkin_build_scripts/10-fzi-sources.list /etc/ros/rosdep/sources.list.d/
    - rosdep update
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@ids-git.fzi.de/Utilities/fzi_styles.git ${HOME}/fzi_styles
    - cp ${HOME}/fzi_styles/.clang-tidy /.clang-tidy
    - rosdep install --from-path . -y --ignore-src --rosdistro ${ROS_DISTRIBUTION}
    - apt-get -y install clang-tidy-6.0
    # Link CMakeLists.txt if multiple packages present
    - if [[ ! -f "CMakeLists.txt"  ]]; then ln -s /opt/ros/${ROS_DISTRIBUTION}/share/catkin/cmake/toplevel.cmake CMakeLists.txt; fi
    - cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    - export TERM=xterm
    - script -qfec "/usr/bin/run-clang-tidy-6.0.py -header-filter=^$(pwd) ." |& tee /tmp/clang-tidy-output.txt
    - echo "There are $(grep 'warning:' /tmp/clang-tidy-output.txt | wc -l) warnings"
    - echo "There are $(grep 'error:' /tmp/clang-tidy-output.txt | wc -l) errors"
    - if [ $(grep -E '(warning:|error:)' /tmp/clang-tidy-output.txt | wc -l) != 0 ]; then exit "1"; fi

  allow_failure: true

.roslint_python:
  tags:
    - docker
  stage: check
  script:
    - apt-get -y update
    - source /opt/ros/${ROS_DISTRIBUTION}/setup.bash
    - git clone ${CI_SCRIPTS_REPO} ${HOME}/ci_scripts
    - cp ${HOME}/ci_scripts/catkin_build_scripts/10-fzi-sources.list /etc/ros/rosdep/sources.list.d/
    - ${HOME}/ci_scripts/catkin_build_scripts/prepare_workspace.sh ${CI_PROJECT_DIR} ${CI_PROJECT_NAME} ${CATKIN_ROOT} ${ROSDISTRO_INDEX_URL}
    - rm -rf /usr/lib/python2.7/dist-packages/OpenSSL
    - rm -rf /usr/lib/python2.7/dist-packages/pyOpenSSL-*
    - pip install pyopenssl
    - mkdir -p ${HOME}/.config
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@ids-git.fzi.de/Utilities/fzi_styles.git ${HOME}/fzi_styles
    - cp ${HOME}/fzi_styles/.config/pylintrc ${HOME}/.config/pylintrc
    - mkdir -p ${CI_PROJECT_DIR}/lint_results
    - cd ${CATKIN_ROOT}/src
    - apt-get install -y bc ros-${ROS_DISTRIBUTION}-roslint
    - ${HOME}/ci_scripts/catkin_build_scripts/roslint.sh ${CATKIN_ROOT} ${CI_PROJECT_DIR}/lint_results
  allow_failure: true
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/lint_results

.run_tests:
  tags:
    - docker
  stage: test
  script:
    - apt-get -y update
    - source /opt/ros/${ROS_DISTRIBUTION}/setup.bash
    - git clone ${CI_SCRIPTS_REPO} ${HOME}/ci_scripts
    - cp ${HOME}/ci_scripts/catkin_build_scripts/10-fzi-sources.list /etc/ros/rosdep/sources.list.d/
    - ${HOME}/ci_scripts/catkin_build_scripts/prepare_workspace.sh ${CI_PROJECT_DIR} ${CI_PROJECT_NAME} ${CATKIN_ROOT} ${ROSDISTRO_INDEX_URL}
    - rosdep install --from-path ${CATKIN_ROOT}/src -y --ignore-src
    - export CATKIN_TEST_COVERAGE=1
    - rm -rf /usr/lib/python2.7/dist-packages/OpenSSL
    - rm -rf /usr/lib/python2.7/dist-packages/pyOpenSSL-*
    - pip install pyopenssl
    - pip install coverage gcovr
    - apt-get install libxml2-utils tree
    - cd ${CATKIN_ROOT}
    - catkin_make
    - source devel/setup.bash
    - cxx_flags="$(cmake --system-information | sed -n 's/CMAKE_CXX_FLAGS == "\(.*\)"/\1/p') --coverage -fprofile-arcs -ftest-coverage"
    - catkin_make run_tests -DCMAKE_CXX_FLAGS="${cxx_flags}"
    - cp -r ${CATKIN_ROOT}/build/test_results ${CI_PROJECT_DIR}/test_results
    - ${HOME}/ci_scripts/catkin_build_scripts/coverage.sh ${CATKIN_ROOT} ${CI_PROJECT_DIR}/code_coverage
    - ${HOME}/ci_scripts/catkin_build_scripts/check_tests.sh ${CATKIN_ROOT}/build/test_results/
    - pip install pycobertura
    - pycobertura show ${CI_PROJECT_DIR}/code_coverage/ros_bt_py/coverage.python.xml
  artifacts:
    when: always
    paths:
      - test_results/
      - code_coverage/

run_tests_xenial:
  image: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_16.04_ros
  variables:
    ROS_DISTRIBUTION: kinetic # This will be overwritten once ROS is sourced
  extends: .run_tests
