include:
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/catkin_pipeline.yml'

industrial_ci_melodic:
  retry:
    max: 1
    when:
      - script_failure
  artifacts:
    when: always
    reports:
      junit: test_results/ros_bt_py/*.xml

industrial_ci_noetic:
  retry:
    max: 1
    when:
      - script_failure
  artifacts:
    when: always
    reports:
      junit: test_results/ros_bt_py/*.xml

variables:
  BUILD_NOETIC: "true"
