---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
        exclude: ((trees/)|(html/))
      - id: end-of-file-fixer
        exclude: ((trees/)|(html/)|(testdata/))
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: ((trees/)|(html/)|(testdata/))
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker  # Forbid UTF-8 byte-order markers
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
  - repo: git@ids-git.fzi.de:Utilities/fzi-pre-commit-hooks.git
    rev: v0.3.1
    hooks:
#      - id: clang-format
      - id: catkin_lint
      - id: roslint-python
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - LICENCE
